language: node_js
node_js:
- "8.9.4"
script: 
  - npm run format:verify
  - npm run lint
  - npm run test
deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    branch: master
